# Neural Document Flow API Server Configuration

[server]
host = "0.0.0.0"
port = 8080
database_url = "sqlite:neural_doc_flow.db"
jwt_secret = "your-secret-key-change-this-in-production"
max_file_size = 104857600  # 100MB
request_timeout = 300      # 5 minutes
rate_limit_rpm = 100       # 100 requests per minute per IP

[neural]
enabled = true
model_path = "./models"
max_threads = 4
timeout = 120
gpu_enabled = false

[security]
enabled = true
level = 2                  # 0-3, higher = more strict
sandbox_enabled = true
timeout = 30
quarantine_hours = 24

[monitoring]
metrics_enabled = true
metrics_interval = 60
tracing_enabled = true
log_level = "info"
profiling_enabled = false

[jobs]
workers = 4
queue_size = 1000
retry_attempts = 3
timeout = 600              # 10 minutes
cleanup_interval = 3600    # 1 hour
retention_seconds = 86400  # 24 hours